@startuml
'https://plantuml.com/class-diagram

abstract class AbstractFlyingObject {
    # int locationX
    # int locationY
    # int speedX
    # int speedY
    # BufferedImage image
    # int width
    # int height
    # boolean isValid

    + AbstractFlyingObject(int locationX, int locationY, int speedX, int speedY)
    + forward():void
    + crash(AbstractFlyingObject flyingObject):boolean
    + setLocation(double locationX, double locationY):void
    + getLocationX():int
    + getLocationY():int
    + getSpeedY():int
    + getImage():BufferedImage
    + getWidth():int
    + getHeight():int
    + notValid():boolean
    + vanish():void
}
abstract class AbstractAircraft extends AbstractFlyingObject {
	# int maxHp
    # int hp
    + AbstractAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + decreaseHp(int decrease):void
    + getHp():int
    + {abstract} shoot():List<Bullet>
 }

abstract class AbstractBullet extends AbstractFlyingObject {
    - int power
    + Bullet(int locationX, int locationY, int speedX, int speedY, int power)
    + forward():void
	+ getPower():int
}

class HeroAircraft extends AbstractAircraft {
    - int shootNum
    - int power
    - int direction
    + HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<Bullet>
}

class MobEnemy extends AbstractAircraft {
    + MobEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<Bullet>
}

class EliteEnemy extends AbstractAircraft {
    + EliteEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<Bullet>
}

class HeroBullet extends AbstractBullet {
    + HeroBullet(int locationX, int locationY, int speedX, int speedY, int power)
}

class EnemyBullet extends AbstractBullet {
    + EnemyBullet(int locationX, int locationY, int speedX, int speedY, int power)
}

abstract class AbstractProp extends AbstractFlyingObject {
    - int power
    + AbstractProp(int locationX, int locationY, int speedX, int speedY)
    + forward():void
	+ {abstract} handleAircrafts(List<AbstractAircraft> enemyAircrafts):void
}

class BloodProp extends AbstractProp {
    # int increaseHp
    + BloodProp(int locationX, int locationY, int speedX, int speedY, int increaseHp)
    + handleAircrafts(List<AbstractAircraft> enemyAircrafts):void
}

class BombProp extends AbstractProp {
    + BombProp(int locationX, int locationY, int speedX, int speedY)
    + handleAircrafts(List<AbstractAircraft> enemyAircrafts):void
}

class BulletProp extends AbstractProp {
    + BulletProp(int locationX, int locationY, int speedX, int speedY)
    + handleAircrafts(List<AbstractAircraft> enemyAircrafts):void
}



@enduml